
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>예외처리</title>
</head>
<body>
    try { 오류가 발생할 수 있는 코드 } <br>
    catch  {오류가 발생했을 때 오류 처리 코드}<br>
    finally {오류 처리와 상관없이 사용했던 리소스들 정리}<br>
    throw { 오류를 발생시킬 때 사용}<br>
    <script>
        try {
            some();  //ReferenceError
           // 5/0;
        }catch(err) {
            console.log(err.message);
        }finally {
            console.log("항상 실행되는 finally 블록");
        }
    </script>
    사용자 정의 예외 발생 <br>
    <script>
        function divide(a, b) {
            if (b === 0) {
                throw new Error("0으로 나눌 수 없습니다!");
            }
            return a/b;
        }

        try{
             const result = divide(10, 0);
             console.log("결과:", result);
         }catch(e){
            console.log("에러:", e.message);
          }
    </script>
    Error객체의 주요 속성 : <br>
    name : 오류 이름 (ReferenceError, TypeError 등)
    message :  오류 메시지  <br>
    stack : 오류가 발생된 코드 위치  <br>
    <script>
        try {
             JSON.parse("{ invalid json }"); // JSON 문법 오류 발생
            }catch (error) {
                console.log("오류 이름:", error.name);
                console.log("오류 메시지:", error.message);
                console.log("오류 스택:", error.stack);
            }
    </script>
    오류 유형별 처리 가능 => catch블럭내부에서 instanceof 타입 비교 조건문 <br>
    <script>
        try {
             JSON.parse("{ invalid json }"); // JSON 문법 오류 발생
            }catch (error) {
                if (error instanceof SyntaxError) {
                    console.log("JSON 문법 오류:", error.message);
                } else if (error instanceof ReferenceError) {
                    console.log("정의되지 않은 변수:", error.message);
                } else {
                    console.log("기타 오류:", error.message);
                }
            }            
    </script>
    기본 Error 객체를 확장하여 사용자 정의 예외(Custom Error)를 만들 수도 있습니다.<br>
    <script>
        class CustomError extends Error {
            constructor(message) {
                super(message);
                this.name = "CustomError";
            }
        }

        function riskyOperation(value) {
            if (value < 0) {
                throw new CustomError("음수 값은 허용되지 않습니다.");
            }
            return Math.sqrt(value);
        }


    </script>

</body>
</html>